### ISSUE TITLE
Controlling error output to the Web

### ISSUE THREAD

**Issue by kaihendry** [schibsted/middy-error-handler#66]
Continuing from https://github.com/schibsted/middy-error-handler/issues/63#issuecomment-1065820544

I noticed https://github.com/middyjs/middy/blob/main/packages/http-error-handler/index.js doesn't seem to use the logger properly like yours does, so I definitely keen on using your package instead of @middy/http-error-handler

But what @middy/http-error-handler has which @schibsted/middy-error-handler doesn't is some sort of expose filter iiuc, to limit showing say the stack trace on 403 errors. Or am I missing something?

**Comment by domeq** [comment]
Yes and no. At the moment exposing the stack trace is only controlled by the `NODE_ENV` values:
https://github.com/schibsted/middy-error-handler/blob/0c1e35580bcb7cb3eb860d4cb3c9654f41b26bf9/index.js#L27

It results in stack traces being filtered out from the live applications, however it doesn't allow you to expose some of them while hiding the rest.

It's not a problem to add the same logic the original Middy's middleware has and check the `expose` property of the error too. However I don't like the middy's behaviour of swallowing all of the response body when `expose` is set to `false`. I understand not exposing the stack trace, but imho the message and error code should always be returned in the same format (always JSON, same keys used.).

**Comment by domeq** [comment]
I've released `3.1.0` version which allows you to pass your own error filtering function and replaces the hardcoded `NODE_ENV` condition I mentioned above with a `exposeStackTrace` option passed to the middleware.
